### ISSUE TITLE
Enable Pruning

### ISSUE THREAD

**Issue by nixbitcoin** [fort-nix/nix-bitcoin#37] opened 2019-04-13 17:52 UTC
**Time Horizon:** Medium term

**Description:** Enable pruning by pulling blocks that have been pruned but are required by clightning from the [Blockstream Explorer](https://blockstream.info)

**Motivation:** Pruning drastically reduces the footprint of the Bitcoin blockchain and therefore improves UX. Clightning might need pruned blocks and could therefore not work on pruned Blockchains. These blocks could be fetched from [Blockstream Explorer](https://blockstream.info) without drastically changing the security model.

**Possible Implementation:** Waiting for comment by @jonasnick

**Comment by darosior** [comment] 2020-05-19 08:14
Hi,

C-lightning does support pruning, as we fetch blocks only once : it can only be a problem if `lightningd` is restarted after a long time (such as `lightningd` known height is < pruned height). I.e. for a (v. roughly) 90 days breathing room a 20G pruned `bitcoind` is acceptable :
```python
>>> 1.5 * 6 * 24 * 90
19440.0
```

> Description: Enable pruning by pulling blocks that have been pruned but are required by clightning from the Blockstream Explorer

With the [Bitcoin backend modularization](https://lightning.readthedocs.io/PLUGINS.html#bitcoin-backend) you could have a mix between [`bcli`](https://github.com/ElementsProject/lightning/blob/master/plugins/bcli.c) (the default backend which polls `bcli`) and something like [`sauron`](https://github.com/lightningd/plugins/tree/master/sauron) or [`esplora_clnd_plugin`](https://github.com/lvaccaro/esplora_clnd_plugin) (they poll the Esplora API).

**Comment by jonasnick** [comment] 2020-05-19 11:29
Hi,

> C-lightning does support pruning

Yes, on my personal node I've been relying on this behavior and it's very easy with nix-bitcoin to enable pruning if you want to. Since running with a pruned node is not documented in the c-lightning repo, I'd be hesitant to recommend this to nix-bitcoin users. Also, when I played with pruning in the past, there were quite a few edge cases were bitcoind would sync and prune too fast for c-lightning to catch up.

**Comment by darosior** [comment] 2020-05-20 09:13
> Since running with a pruned node is not documented in the c-lightning repo,

There is now [a section in the README](https://github.com/ElementsProject/lightning/#pruning) :)
But I understand.

**Comment by jonasnick** [comment] 2020-05-20 13:30
@darosior Thanks! That's excellent. @nixbitcoin how about we close this issue once we remove the note about pruning in the README? Perhaps we can add a `FIXME` to the configuration.nix to enable pruning (but only if not lnd and with a link to the clightning README).

**Comment by nixbitcoin** [comment] 2020-05-21 08:30
> @nixbitcoin how about we close this issue once we remove the note about pruning in the README? Perhaps we can add a `FIXME` to the configuration.nix to enable pruning (but only if not lnd and with a link to the clightning README).

Will do

**Comment by Kixunil** [comment] 2020-05-22 05:46
I've been thinking for some time to write an RPC proxy (similar to [`btc-rpc-proxy`](https://github.com/Kixunil/btc-rpc-proxy)) that would auto-detect missing blocks and fetch them from a random node (optionaly over Tor). Also same hack for txindex (keep optimized index that can point inside missing blocks).

Do you think it'd be an interesting idea? Anyone would be interested to participate? I may be able to start working on it in a few months. I'd pick Rust, of course, but if someone wants to write it sooner using something else and doing most of the work I'd try to find time for contributions.

Another thing that you may find inspiring, I already solve the problem of correctly setting pruning depending on which packages are installed in my Debian repository. I do it by requiring one of three small packages that set the configuration. The rules are:

* `bitcoin-mainnet` depends on `bitcoin-pruned-mainnet` (default) or `bitcoin-fullchain-mainnet` (means no pruning) or `bitcoin-txindex-mainnet`
* All of those packages provide a single file placed in `/etc/bitcoin-mainnet/chain_mode` which is concatenated with the rest of configuration to produce the config file for bitcoind
* Things that don't need full chain or txindex (e.g. NBXplorer) depend on `bitcoin-mainnet` only
* Things that need fullchain depend on both `bitcoin-mainnet` and `bitcoin-fullchain-mainnet`
* txindex works pretty much same as above
* txindex package declares `Provides: bitcoin-fullchain-mainnet`, which means that it can satisfy the dependency (thus, if two one package depends on fullchain and the other on txindex, it won't cause a conflict)

This makes it impossible for the software to break, unless the admin messes up with the files (it's documented that he must not) or the disk space runs out. :)

In case someone has desire to try my repo to see it in action - it's currently broken, I already know the root cause, will fix it today unless an asteroid strikes me. :laughing:

**Comment by nixbitcoin** [comment] 2020-06-01 17:51
> I do it by requiring one of three small packages that set the configuration.

Can we just make options depend on eachother? This reminds me that the `configuration.nix` points out certain services that can only be enabled if others are also enabled. Maybe we could enforce these hints in `configuration.nix`'s comments by making the relevant enable options depend on eachother.

> Do you think it'd be an interesting idea? Anyone would be interested to participate? I may be able to start working on it in a few months. I'd pick Rust, of course, but if someone wants to write it sooner using something else and doing most of the work I'd try to find time for contributions.

Very good idea and would integrate it into nix-bitcoin.

**Closed** 2020-06-17 09:26 UTC
Labels: Short Term, enhancement
