### ISSUE TITLE
Checking runtime dependencies for pyln_proto-24.8.2-py3-none-any.whl  > - cryptography<43,>=42 not satisfied by version 43.0.1

### ISSUE THREAD

**Issue by hbakardzhiev** [fort-nix/nix-bitcoin#749] opened 2024-12-05 11:56 UTC
Hey, updated my nix-bitcoin installation and I am getting this failure.
```
warning: Git tree '/etc/nixos' is dirty
error: builder for '/nix/store/6jp0rq3nmd50gj7sv8cz84v7hablhwhq-python3.12-pyln-proto-24.08.2.drv' failed with exit code 1;
       last 25 log lines:
       > Sourcing python-namespaces-hook
       > Sourcing python-catch-conflicts-hook.sh
       > Sourcing pytest-check-hook
       > Using pytestCheckPhase
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/63npmx00nn25pili2hif8y1jqd43mvsz-clightning-v24.08.2.zip
       > source root is clightning-v24.08.2
       > setting SOURCE_DATE_EPOCH to timestamp 1729209600 of file clightning-v24.08.2/contrib/pyln-proto/tests/vectors/onion-test-v0.json
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > Executing pypaBuildPhase
       > Creating a wheel...
       > pypa build flags: --no-isolation --outdir dist/ --wheel
       > * Getting build dependencies for wheel...
       > * Building wheel...
       > Successfully built pyln_proto-24.8.2-py3-none-any.whl
       > Finished creating a wheel...
       > Finished executing pypaBuildPhase
       > Running phase: pythonRuntimeDepsCheckHook
       > Executing pythonRuntimeDepsCheck
       > Checking runtime dependencies for pyln_proto-24.8.2-py3-none-any.whl
       >   - cryptography<43,>=42 not satisfied by version 43.0.1
       For full logs, run 'nix log /nix/store/6jp0rq3nmd50gj7sv8cz84v7hablhwhq-python3.12-pyln-proto-24.08.2.drv'.
error: 1 dependencies of derivation '/nix/store/a1pxdrs4qsvkr9iv3sr0qs1jgws1ryd2-python3.12-clnrest-24.08.2.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vjgximfsc30j5cfq5sxw1zasni84gdkq-config.drv' failed to build
error: 1 dependencies of derivation '/nix/store/nwn0b2zpisbn8yavxxkqakk4kj622nqh-unit-script-clightning-pre-start.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5pna11f7cnm5fgrd9chm0bxklrcnsqv9-unit-clightning.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/yjrkp5g092p5ric5nv4kh4in5wn7d86j-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/xqfaipagf9i56gywaj9qylidd79fgsbl-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dl2lic7s6x0x2586c7i83jc51743qnza-nixos-system-bob-25.05.20241203.55d15ad.drv' failed to build
```

**Comment by erikarvstedt** [comment] 2024-12-05 13:16
Duplicate of https://github.com/fort-nix/nix-bitcoin/issues/513. See https://github.com/fort-nix/nix-bitcoin/issues/513 on how to fix this.

**Closed by erikarvstedt** 2024-12-05 13:16 UTC

**Comment by hbakardzhiev** [comment] 2024-12-07 15:50
Thank you for the help, it worked
