### ISSUE TITLE
error: The option `services.duplicity.includeFileList' does not exist. 

### ISSUE THREAD

**Issue by nullcount** [fort-nix/nix-bitcoin#729] opened 2024-08-18 06:12 UTC
I believe this is a bug, maybe duplicity config option has been renamed. 

I had no issues deploying with krops. However, I wanted to try to deploy as a module.

I cloned this repo into `/etc/nixos`

I modified the `/etc/nixos/configuration.nix` to import `secure-node.nix` like this:

```
imports = [
    ./nix-bitcoin/modules/presets/secure-node.nix
    ./hardware-configuration.nix
  ];
```

However, I get this error during `nixos-rebuild switch`: 

```
error: The option `services.duplicity.includeFileList' does not exist. Definition values:
       - In `/etc/nixos/nix-bitcoin/modules/backups.nix':
           {
             _type = "if";
             condition = false;
             content = "/nix/store/j1wsk8vz54jlqib2cnfiw8bbczrr1iyz-filelist.txt";
           }
```
I'm not using backups, so I remove the line`./backups.nix` from `modules/modules.nix`
I also remove the line `services.backups.frequency = "daily";` from `modules/presets/secure-node.nix`

After removing these lines, I was able to build from the configuration as expected.

**Comment by erikarvstedt** [comment] 2024-08-18 08:40
Duplicate of #725.

**Closed by erikarvstedt** 2024-08-18 08:40 UTC
